# -*- coding: utf-8 -*-
"""vehiclesystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hfm7W4KFbXUXfAQXlk3Ql_bqi73YVGi8
"""

import hashlib
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.hazmat.primitives import serialization

def generate_sha256():
    message = input("Enter message: ")
    hash_value = hashlib.sha256(message.encode()).hexdigest()
    print(f"SHA-256 Hash: {hash_value}")


private_key = None
public_key = None

def generate_keys():
    global private_key, public_key
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    public_key = private_key.public_key()
    print(" Public and Private keys generated!")


def sign_message():
    global private_key
    if private_key is None:
        print(" Generate keys first!")
        return

    message = input("Enter message to sign: ")

    signature = private_key.sign(
        message.encode(),
        padding.PSS(
            mgf=padding.MGF1(hashes.SHA256()),
            salt_length=padding.PSS.MAX_LENGTH
        ),
        hashes.SHA256()
    )

    print(f"Signature (hex): {signature.hex()}")
    return message, signature


def verify_signature(message, signature):
    global public_key
    if public_key is None:
        print(" Generate keys first!")
        return

    try:
        public_key.verify(
            signature,
            message.encode(),
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()),
                salt_length=padding.PSS.MAX_LENGTH
            ),
            hashes.SHA256()
        )
        print(" Signature is VALID")
    except:
        print(" Signature is INVALID")


vehicles = {}

def register_vehicle():
    plate = input("Enter Number Plate: ")

    if plate in vehicles:
        print(" Vehicle already registered!")
        return

    owner = input("Enter Owner Name: ")
    model = input("Enter Vehicle Model: ")

    vehicles[plate] = {"owner": owner, "model": model}
    print(" Vehicle registered successfully!")


def get_vehicle():
    plate = input("Enter Number Plate: ")

    if plate not in vehicles:
        print(" Vehicle not found!")
        return

    print(f"Owner: {vehicles[plate]['owner']}")
    print(f"Model: {vehicles[plate]['model']}")



def menu():
    last_signed_message = None
    last_signature = None

    while True:
        print("\n====== Cryptography & Vehicle System ======")
        print("1. Generate SHA-256 Hash")
        print("2. Generate Key Pair")
        print("3. Sign Message")
        print("4. Verify Signature")
        print("5. Register Vehicle")
        print("6. Get Vehicle Details")
        print("7. Exit")

        choice = input("Enter choice: ")

        if choice == "1":
            generate_sha256()

        elif choice == "2":
            generate_keys()

        elif choice == "3":
            result = sign_message()
            if result:
                last_signed_message, last_signature = result

        elif choice == "4":
            if last_signed_message and last_signature:
                verify_signature(last_signed_message, last_signature)
            else:
                print(" No message signed yet!")

        elif choice == "5":
            register_vehicle()

        elif choice == "6":
            get_vehicle()

        elif choice == "7":
            print("Exiting...")
            break

        else:
            print(" Invalid choice!")



menu()